# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '/home/vsts/work/1/s/target'
    ArtifactName: 'sbom'
    publishLocation: 'Container'
#- task: CmdLine@2
#  inputs:
#    script: 'curl --location --request POST ''http://3.128.205.114:8081/api/v1/bom'' --header ''X-Api-Key:XKCCVYXgea4QWCv8DOBj1Y3WyxkjuEHP'' --form ''project="b74cb31a-e0dc-49d8-bf82-96010cf9e1f3"'' --form ''bom=@"/home/vsts/work/1/s/target/sbom.json"'''