name: dep-track

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: '/home/runner/work/simple-java-maven-app/simple-java-maven-app/target/*'
    - name: bom upload
      run: curl --location --request POST 'http://3.128.205.114:8081/api/v1/bom' --header 'X-Api-Key:XKCCVYXgea4QWCv8DOBj1Y3WyxkjuEHP' --form 'project="cd1c4f57-a45f-4188-98fe-4714ec6b3a56"' --form 'bom=@"/home/runner/work/java-reachability-playground/java-reachability-playground/target/sbom.json"'
    
